# Generated by Django 5.2.8 on 2025-11-27 07:32

import apps.tcc.utils.snowflake
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the member", max_length=120
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary email for login and communication",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, help_text="Age for ministry grouping", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "testimony",
                    models.TextField(
                        blank=True, help_text="Personal testimony or spiritual journey"
                    ),
                ),
                ("baptism_date", models.DateField(blank=True, null=True)),
                ("membership_date", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("staff", "Staff"),
                            ("ministry_leader", "Ministry Leader"),
                            ("member", "Member"),
                            ("visitor", "Visitor"),
                        ],
                        default="visitor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Approval"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("service", "Church Service"),
                            ("meeting", "Meeting"),
                            ("study_group", "Study Group"),
                            ("social", "Social Event"),
                            ("volunteer", "Volunteer Event"),
                            ("youth", "Youth Event"),
                            ("prayer", "Prayer Meeting"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("Upcoming", "Upcoming"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("checked_in", "Checked In"),
                            ("pending", "Pending"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tcc.event",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_registrations",
                "unique_together": {("event", "user")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="events_attended",
                through="tcc.EventRegistration",
                through_fields=("event", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FundType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fundraising target",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current fund balance",
                        max_digits=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Type",
                "verbose_name_plural": "Fund Types",
                "db_table": "fund_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the prayer request", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Prayer request details")),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("congregation", "Congregation Only"),
                            ("leaders_only", "Leaders Only"),
                            ("private", "Private"),
                        ],
                        default="congregation",
                        help_text="Who can see this prayer request",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("healing", "Healing"),
                            ("guidance", "Guidance"),
                            ("thanksgiving", "Thanksgiving"),
                            ("financial", "Financial"),
                            ("family", "Family"),
                            ("other", "Other"),
                            ("general", "General"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("answered", "Answered"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer_notes",
                    models.TextField(
                        blank=True, help_text="Notes about how the prayer was answered"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this prayer request expires",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Request",
                "verbose_name_plural": "Prayer Requests",
                "db_table": "prayer_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerResponse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "content",
                    models.TextField(help_text="Prayer response or support message"),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this response is private to the prayer request owner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prayer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tcc.prayer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer Response",
                "verbose_name_plural": "Prayer Responses",
                "db_table": "prayer_responses",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INVALID_CREDENTIALS", "Invalid Credentials"),
                            ("ACCOUNT_LOCKOUT", "Account Lockout"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("TOKEN_REVOKED", "Token Revoked"),
                            ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(help_text="Sermon title", max_length=200)),
                (
                    "preacher",
                    models.CharField(
                        help_text="Name of preacher/pastor", max_length=120
                    ),
                ),
                (
                    "bible_passage",
                    models.CharField(
                        blank=True,
                        help_text="Bible reference (e.g., John 3:16)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Sermon summary"),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Full sermon content/notes"),
                ),
                ("sermon_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Sermon duration in minutes", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sermon",
                "verbose_name_plural": "Sermons",
                "db_table": "sermons",
                "ordering": ["-sermon_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("object_id", models.BigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Field-level changes"),
                ),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="tcc_auditlo_content_9619db_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="tcc_auditlo_timesta_b78db0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="tcc_auditlo_user_id_2d0f66_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "action"],
                        name="tcc_auditlo_resourc_135b5e_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="tcc_auditlo_action_2c0161_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=apps.tcc.utils.snowflake.generate_snowflake_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Donation amount", max_digits=10
                    ),
                ),
                (
                    "donation_date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 11, 27, 14, 32, 40, 685167)
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Is this a recurring donation?"
                    ),
                ),
                (
                    "recurring_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        help_text="Frequency for recurring donations",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, help_text="Donation receipt number", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to="tcc.fundtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "db_table": "donations",
                "ordering": ["-donation_date"],
                "indexes": [
                    models.Index(
                        fields=["donation_date", "status"],
                        name="donations_donatio_1476b4_idx",
                    ),
                    models.Index(
                        fields=["donor", "donation_date"],
                        name="donations_donor_i_7c2fb2_idx",
                    ),
                    models.Index(
                        fields=["fund", "status"], name="donations_fund_id_3e01a6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="prayer",
            index=models.Index(
                fields=["privacy", "status"], name="prayer_requ_privacy_65bce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prayer",
            index=models.Index(
                fields=["user", "created_at"], name="prayer_requ_user_id_a20e52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prayer",
            index=models.Index(
                fields=["category", "is_answered"],
                name="prayer_requ_categor_8abe1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sermon",
            index=models.Index(
                fields=["sermon_date"], name="sermons_sermon__acbe27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sermon",
            index=models.Index(fields=["preacher"], name="sermons_preache_85a887_idx"),
        ),
        migrations.AddIndex(
            model_name="sermon",
            index=models.Index(fields=["status"], name="sermons_status_358da4_idx"),
        ),
    ]
