# Generated by Django 5.2.8 on 2025-11-29 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc", "0002_remove_user_age_alter_donation_donation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 29, 23, 53, 40, 291751)
            ),
        ),
    ]
