# Generated by Django 5.2.8 on 2025-12-04 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc", "0003_alter_donation_donation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 4, 17, 3, 58, 468576)
            ),
        ),
    ]
