# Generated by Django 5.2.8 on 2026-01-23 17:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tcc", "0005_alter_donation_donation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 24, 0, 47, 28, 56876)
            ),
        ),
    ]
