# Generated by Django 5.2.8 on 2026-01-25 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc", "0006_alter_auditlog_content_type_alter_auditlog_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 25, 16, 5, 55, 411936)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("upcoming", "Upcoming"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("admin", "Administrator"),
                    ("staff", "Staff"),
                    ("ministry_leader", "Ministry Leader"),
                    ("member", "Member"),
                    ("visitor", "Visitor"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
    ]
