# Generated by Django 5.2.8 on 2026-01-25 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc", "0007_alter_donation_donation_date_alter_event_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 25, 16, 11, 23, 484820)
            ),
        ),
    ]
