# Generated by Django 5.2.8 on 2026-01-25 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcc", "0009_alter_donation_donation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 25, 20, 46, 32, 806462)
            ),
        ),
    ]
