# error_codes.py
from enum import Enum

class ErrorCode(Enum):
    """
    Unified error codes for all domains in the church management system
    """
    
    # ===== GENERAL ERRORS =====
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    INVALID_OPERATION = "INVALID_OPERATION"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    
    # ===== TECHNICAL ERRORS =====
    DATA_ACCESS_ERROR = "DATA_ACCESS_ERROR"
    REPOSITORY_ERROR = "REPOSITORY_ERROR"
    SECURITY_ERROR = "SECURITY_ERROR"
    SESSION_ERROR = "SESSION_ERROR"
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    DATABASE_TIMEOUT = "DATABASE_TIMEOUT"
    INTEGRITY_VIOLATION = "INTEGRITY_VIOLATION"
    DEADLOCK_DETECTED = "DEADLOCK_DETECTED"
    CONNECTION_POOL_EXHAUSTED = "CONNECTION_POOL_EXHAUSTED"
    TRANSACTION_ERROR = "TRANSACTION_ERROR"
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
    BULK_OPERATION_FAILED = "BULK_OPERATION_FAILED"
    
    # ===== USER DOMAIN =====
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    ACCOUNT_PENDING = "ACCOUNT_PENDING"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_AGE = "INVALID_AGE"
    MEMBERSHIP_STATUS_ERROR = "MEMBERSHIP_STATUS_ERROR"
    BAPTISM_RECORD_ERROR = "BAPTISM_RECORD_ERROR"
    FAMILY_RELATIONSHIP_ERROR = "FAMILY_RELATIONSHIP_ERROR"
    MINISTRY_ASSIGNMENT_ERROR = "MINISTRY_ASSIGNMENT_ERROR"
    USER_IMPORT_ERROR = "USER_IMPORT_ERROR"
    
    # ===== EVENT DOMAIN =====
    EVENT_FULL = "EVENT_FULL"
    EVENT_REGISTRATION_CLOSED = "EVENT_REGISTRATION_CLOSED"
    EVENT_CANCELLED = "EVENT_CANCELLED"
    EVENT_NOT_STARTED = "EVENT_NOT_STARTED"
    EVENT_ENDED = "EVENT_ENDED"
    ALREADY_REGISTERED = "ALREADY_REGISTERED"
    NOT_REGISTERED = "NOT_REGISTERED"
    CHECKIN_EXPIRED = "CHECKIN_EXPIRED"
    EVENT_SCHEDULE_CONFLICT = "EVENT_SCHEDULE_CONFLICT"
    MAX_ATTENDEES_EXCEEDED = "MAX_ATTENDEES_EXCEEDED"
    EVENT_PUBLISH_ERROR = "EVENT_PUBLISH_ERROR"
    EVENT_CANCEL_ERROR = "EVENT_CANCEL_ERROR"
    EVENT_UPDATE_ERROR = "EVENT_UPDATE_ERROR"
    
    # ===== SERMON DOMAIN =====
    SERMON_MEDIA_NOT_FOUND = "SERMON_MEDIA_NOT_FOUND"
    SERMON_ALREADY_PUBLISHED = "SERMON_ALREADY_PUBLISHED"
    MEDIA_UPLOAD_FAILED = "MEDIA_UPLOAD_FAILED"
    MEDIA_PROCESSING_ERROR = "MEDIA_PROCESSING_ERROR"
    INVALID_MEDIA_TYPE = "INVALID_MEDIA_TYPE"
    MEDIA_STORAGE_ERROR = "MEDIA_STORAGE_ERROR"
    BIBLE_REFERENCE_INVALID = "BIBLE_REFERENCE_INVALID"
    SERMON_PUBLISH_ERROR = "SERMON_PUBLISH_ERROR"
    SERMON_ARCHIVE_ERROR = "SERMON_ARCHIVE_ERROR"
    MEDIA_DURATION_INVALID = "MEDIA_DURATION_INVALID"
    
    # ===== PRAYER DOMAIN =====
    PRAYER_REQUEST_NOT_PUBLIC = "PRAYER_REQUEST_NOT_PUBLIC"
    PRAYER_REQUEST_ALREADY_ANSWERED = "PRAYER_REQUEST_ALREADY_ANSWERED"
    PRAYER_REQUEST_EXPIRED = "PRAYER_REQUEST_EXPIRED"
    PRAYER_RESPONSE_NOT_ALLOWED = "PRAYER_RESPONSE_NOT_ALLOWED"
    PRAYER_CATEGORY_INVALID = "PRAYER_CATEGORY_INVALID"
    PRAYER_PRIVACY_VIOLATION = "PRAYER_PRIVACY_VIOLATION"
    PRAYER_ANSWER_UPDATE_ERROR = "PRAYER_ANSWER_UPDATE_ERROR"
    PRAYER_RESPONSE_PRIVACY_ERROR = "PRAYER_RESPONSE_PRIVACY_ERROR"
    
    # ===== DONATION DOMAIN =====
    DONATION_AMOUNT_INVALID = "DONATION_AMOUNT_INVALID"
    DONATION_PAYMENT_FAILED = "DONATION_PAYMENT_FAILED"
    DONATION_RECURRING_CANCEL_FAILED = "DONATION_RECURRING_CANCEL_FAILED"
    PAYMENT_METHOD_INVALID = "PAYMENT_METHOD_INVALID"
    FUND_INACTIVE = "FUND_INACTIVE"
    FUND_TARGET_REACHED = "FUND_TARGET_REACHED"
    RECEIPT_GENERATION_FAILED = "RECEIPT_GENERATION_FAILED"
    TRANSACTION_DECLINED = "TRANSACTION_DECLINED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    RECURRING_DONATION_ERROR = "RECURRING_DONATION_ERROR"
    DONATION_REFUND_ERROR = "DONATION_REFUND_ERROR"
    
    # ===== CHAT DOMAIN =====
    CHAT_ROOM_FULL = "CHAT_ROOM_FULL"
    MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED"
    CHAT_NOT_ALLOWED = "CHAT_NOT_ALLOWED"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    CHAT_ROOM_NOT_FOUND = "CHAT_ROOM_NOT_FOUND"
    MESSAGE_EDIT_EXPIRED = "MESSAGE_EDIT_EXPIRED"
    MESSAGE_DELETE_EXPIRED = "MESSAGE_DELETE_EXPIRED"
    CHAT_PARTICIPANT_LIMIT = "CHAT_PARTICIPANT_LIMIT"
    CHAT_ROOM_ARCHIVED = "CHAT_ROOM_ARCHIVED"
    
    # ===== EXTERNAL SERVICES =====
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    PAYMENT_GATEWAY_ERROR = "PAYMENT_GATEWAY_ERROR"
    EMAIL_SERVICE_ERROR = "EMAIL_SERVICE_ERROR"
    SMS_SERVICE_ERROR = "SMS_SERVICE_ERROR"
    STORAGE_SERVICE_ERROR = "STORAGE_SERVICE_ERROR"

class Domain(Enum):
    """Domain identifiers for error categorization"""
    USER = "USER"
    EVENT = "EVENT"
    SERMON = "SERMON"
    PRAYER = "PRAYER"
    DONATION = "DONATION"
    CHAT = "CHAT"
    SYSTEM = "SYSTEM"
    AUTHENTICATION = "AUTHENTICATION"
    DATABASE = "DATABASE"

class ErrorSeverity(Enum):
    """Error severity levels"""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"